### ISSUE TITLE
Can't get an API Token

### ISSUE THREAD

**Issue by BestRazer** [CheweyZ/discord-bot-analytics#1]
I can't find where I can get an API Token on this website [https://api-docs.chewey-bot.top/](https://api-docs.chewey-bot.top/).

**Comment by CheweyZ** [comment]
Sorry for the delay, to get an API key please join the Discord and DM Chewey Bot "!claim-api-key"
The swagger docs have also been reverted to help clear this up (If you visit https://api.chewey-bot.top )
